language: php

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6

addons:
  hosts:
    - simplesamlphp.test
  firefox: "35.0.1"
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

env:
  global:
    # Our behat tests are designed for Moodle 31+
    - RUN_BEHAT=no
  matrix:
    - MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql

matrix:
  include:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_31_STABLE RUN_BEHAT=yes DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_32_STABLE RUN_BEHAT=yes DB=mysqli

before_install:
  - if [ "$RUN_BEHAT" = "yes" ]; then tests/idp/simplesamlphp.sh; fi
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - git config --global "url.https://github.com/.insteadOf" "git@github.com:"
  - moodle-plugin-ci install -vvv
  - echo '$CFG->cookiesecure = false;' >> moodle/config.php

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
# - moodle-plugin-ci validate   # TODO need to fix the table names
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - if [ "$RUN_BEHAT" = "yes" ]; then moodle-plugin-ci behat; fi

after_script:
  - cat /tmp/behat_screenshots.base64
